name: Publish package
on:
   release:
     types: [published]
jobs:
  pypi:
    name: Publish package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt
          pip3 install .
          pip3 install django-nose==1.4.7
          pip3 install setuptools wheel
      - name: Run Tests
        run: |
          python manage.py test
      - name: Build
        run: |
          python setup.py sdist bdist_wheel
      - name: Publish
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true
