name: Sonar
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
  schedule:
    - cron: 0 16 * * *  
jobs:
  sonarcloud:
    name: Sonar
    runs-on: ubuntu-latest
    steps:
      - name: Get Branch name
        id: branchName
        run: |
         echo ::set-output name=branch::$(echo $PR_COMMENT | cut -d "[" -f2 | cut -d "]" -f1)
        env:
          PR_COMMENT: ${{ github.event.comment.body }}
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.branchName.outputs.branch }}
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          pip3 install -r django_bootstrap_swt/requirements.txt
          pip3 install -r tests/requirements.txt
      - name: Run Tests
        run: |
          python manage.py test
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.branch.name=${env.steps.branchName.outputs.branch}
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          SONAR_TOKEN: '${{ secrets.SONAR_TOKEN }}'
