name: Sonar
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
  schedule:
    - cron: 0 16 * * *  
jobs:
  sonarcloud:
    name: Sonar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nelonoel/branch-name@v1.0.1
      # Use branch name for whatever purpose
      - run: echo ${BRANCH_NAME}
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt
          pip3 install .
          pip3 install django-nose==1.4.7
      - name: Run Tests
        run: |
          python manage.py test
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.branch.name=$BRANCH_NAME
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          SONAR_TOKEN: '${{ secrets.SONAR_TOKEN }}'
